后端/Club/ClubWeb/allclub/urls.py
from django.urls import path

from . import views

app_name = 'allclub'

urlpatterns = [
    path('', views.index,name='index'),
    # path('activity/',views.clubactive,name='activity'),
]

后端/Club/ClubWeb/chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
   path('', views.index, name='index'),
   path('<str:room_name>/', views.room, name='room'),
   path('one2one/<str:one2oneroom_name>/',views.one,name='one2oneroom')
]

后端/Club/ClubWeb/signinaout/urls.py
from django.urls import path,include

from . import views

app_name = 'signinaout'

urlpatterns = [
    path('login/', views.login,name='login'),
    path('logout/', views.logout,name='logout'),
    path('register/', views.register,name='register'),
    path('changes/',views.changes,name='changes'),
    path('confirm/',views.user_confirm,name='comfirm'),
    path('idconfirm/',views.idconfirm,name='idconfirm'),
    path('change_password/',views.change_password,name='change_password'),
    path('change_password_confirm/',views.change_password_confirm,name='change_password_confirm'),
]

后端/Club/ClubWeb/signinaout/models.py
from django.db import models


# MEDIA_ADDR = 'http://localhost:8000/media/'
# Create your models here.
class User(models.Model):
    gender = (
        ('male','男'),
        ('female','女'),
    )
    status = (
        ('normal','普通用户'),
        ('proprieter','社团负责人'),
        ('administrator','管理员'),
    )
    name = models.CharField(max_length=255,unique=True)
    password = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    sex = models.CharField(max_length=32,choices=gender,default="男")
    c_time = models.DateTimeField(auto_now_add=True)
    has_confirmed = models.BooleanField(default=False)
    user_type = models.CharField(max_length=255,choices=status,default='普通用户')
    head_image = models.ImageField(upload_to='user_head/',default='',verbose_name='头像')
    check_image = models.ImageField(upload_to='id_check/',default='id_check/check_default.png',verbose_name='身份信息卡')
    id_checked = models.BooleanField(default=False)


    def __str__(self):
        return self.name
    # def get_avatar_url(self):
    #     return MEDIA_ADDR + str(self.avatar)

    class Meta:
        ordering = ["-c_time"]
        verbose_name = "用户"
        verbose_name_plural = "用户"

class ConfirmString(models.Model):
    code = models.CharField(max_length=256)
    user = models.OneToOneField('User',on_delete=models.CASCADE)
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.name + ":  " + self.code

    class Meta:
        ordering = ['-c_time']
        verbose_name = '确认码'
        verbose_name_plural = '确认码'

class ChangePasswordConfirmString(models.Model):
    code = models.CharField(max_length=256)
    user = models.OneToOneField('User',on_delete=models.CASCADE)
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.name + ":  " + self.code

    class Meta:
        ordering = ['-c_time']
        verbose_name = '修改密码确认码'
        verbose_name_plural = '修改密码确认码'

后端/Club/ClubWeb/signinaout/forms.py
from django import forms
from captcha.fields import CaptchaField

class UserForm(forms.Form):
    username = forms.CharField(label="用户名",max_length=255)
    password = forms.CharField(label="密码",max_length=255,widget=forms.PasswordInput)
    captcha = CaptchaField(label='验证码')

class RegisterForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput())
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput())
    password2 = forms.CharField(label="确认密码", max_length=256,
                                widget=forms.PasswordInput())
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput())
    sex = forms.ChoiceField(label='性别', choices=gender)
    captcha = CaptchaField(label='验证码')
    head_image = forms.ImageField(label='用户头像')

class ChangeForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput())
    sex = forms.ChoiceField(label='性别', choices=gender)

class IdCkeckForm(forms.Form):
    check_image = forms.ImageField(label='身份验证信息')

class ChangePassword(forms.Form):
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput())
    new_password = forms.CharField(label="新密码", max_length=256, widget=forms.PasswordInput())
    # old_password = forms.CharField(label="原密码", max_length=256, widget=forms.PasswordInput())
    captcha = CaptchaField(label='验证码')

后端/Club/ClubWeb/signinaout/views.py
from django.shortcuts import render,redirect
from django.contrib import auth

from . import models
from . import forms
from django.conf import settings

import hashlib
import datetime

# Create your views here.

def make_confirm_string(user):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    # 将用户名和当前时间作为主体和盐，生成验证码
    code = hash_code(user.name,now)
    # 保存用户的验证码
    models.ConfirmString.objects.create(code=code,user=user)
    return code

def make_change_password_confirm_string(user):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    # 将用户名和当前时间作为主体和盐，生成验证码
    code = hash_code(user.name,now)
    # 保存用户的验证码
    models.ChangePasswordConfirmString.objects.create(code=code,user=user)
    return code

def send_email(email,code):
    from django.core.mail import EmailMultiAlternatives
    # 邮件主题
    subject = '来自localhost:8000/allclubs的注册确认邮件'
    # 文本格式的邮件内容
    text_content = '''感谢注册localhost:8000/allclubs，这里是社团资讯中心，专注于最新最全面的社团活动等信息分享！\
                        如果你看到这条消息，说明你的邮箱服务器不提供HTML链接功能，请联系管理员！'''
    # html格式的邮件内容
    html_content = '''
                        <p>感谢注册<a href="http://{}info/confirm/?code={}" target=blank>localhost:8000/allclubs</a>，\
                        这里是社团资讯中心，专注于最新最全面的社团活动等信息分享！</p>
                        <p>请点击站点链接完成注册确认！</p>
                        <p>此链接有效期为{}天！</p>
                        '''.format('localhost:8000/', code, settings.CONFIRM_DAYS)
    # 将邮件信息打包
    msg = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()
def send_change_password_email(email,code,new):
    from django.core.mail import EmailMultiAlternatives
    # 邮件主题
    subject = '来自localhost:8000/allclubs的修改密码的确认邮件'
    # 文本格式的邮件内容
    text_content = '''您在localhost:8000/allclubs注册账号的密码已正在被修改，若非本人操作请无视此邮件！\
                        如果你看到这条消息，说明你的邮箱服务器不提供HTML链接功能，请联系管理员！'''
    # html格式的邮件内容
    html_content = '''
                        <p>您在<a href="http://{}info/change_password_confirm/?code={}&new={}" target=blank>localhost:8000/allclubs</a>，\
                        注册账号的密码已正在被修改，若非本人操作请无视此邮件！</p>
                        <p>请点击站点链接完成密码修改确认！</p>
                        <p>此链接有效期为{}天！</p>
                        '''.format('localhost:8000/', code, new , settings.CONFIRM_DAYS)
    # 将邮件信息打包
    msg = EmailMultiAlternatives(subject, text_content, settings.EMAIL_HOST_USER, [email])
    msg.attach_alternative(html_content, "text/html")
    msg.send()

# 密码加密
def hash_code(s,salt='Clubs'):
    # salt增加密码的复杂程度，使用sha256加密
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())
    return h.hexdigest()

# login func
def login(request):
    # 使用session 不允许重复登录
    if request.session.get('is_login',None):
        return redirect('/allclubs/')
    # 判断请求方式
    if request.method == 'POST':
        # 实例化form表单
        login_form = forms.UserForm(request.POST)
        message = '请检查填写的内容！'
        if login_form.is_valid():
            # 完成数据格式校验
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            try:
                user = models.User.objects.get(name=username)
            except:
                message = '用户名不存在'
                return render(request,'signinaout/login.html', locals())

            if not user.has_confirmed:
                message = '该用户还未经过邮件确认！'
                return render(request, 'signinaout/login.html', locals())

            # 判定输入密码和数据库中密码一致
            if user.password == hash_code(password):
                request.session['is_login'] = True
                request.session['user_id'] = user.id
                request.session['user_name'] = user.name
                request.session['id_checked'] = user.id_checked
                # 如果密码正确就重定向到/allclubs/页面
                return redirect('/allclubs/')
            else:
                message = '密码不正确'
                return render(request,'signinaout/login.html', locals())
        else:
            return render(request,'signinaout/login.html',locals())
    login_form = forms.UserForm()
    return render(request,'signinaout/login.html', locals())

# logout func
def logout(request):
    # 如果未登录就没必要退出了，重定向到登陆界面
    if not request.session.get('is_login',None):
        return redirect('/info/login/')
    # 清空session信息
    request.session.flush()
    # 返回退出页面
    return render(request,'signinaout/logout.html')
# register func
def register(request):
    # 如果已经登录了就不再允许注册
    if request.session.get('is_login',None):
        return redirect('/allclubs/')
    # 如果没有登录并且有提交信息
    if request.method == 'POST':
        # 实例化表单
        register_form = forms.RegisterForm(request.POST,request.FILES)
        message = '请检查填写的内容！'
        # 对表单内容进行校验
        if register_form.is_valid():
            print('已经进入校验')
            username = register_form.cleaned_data.get('username')
            password1 = register_form.cleaned_data.get('password1')
            password2 = register_form.cleaned_data.get('password2')
            email = register_form.cleaned_data.get('email')
            sex = register_form.cleaned_data.get('sex')
            head_image = register_form.cleaned_data.get('head_image')
            # 判断第一次和第二次输入的密码是否是同一个
            if password1 != password2:
                message = '两次输入的密码不同！'
                return render(request,'signinaout/register.html',locals())
            else:
                same_name_user = models.User.objects.filter(name=username)
                if same_name_user:
                    message = '用户名已经存在'
                    return render(request,'signinaout/register.html',locals())
                same_email_user = models.User.objects.filter(email=email)
                if same_email_user:
                    message = '该邮箱已经被注册了！'
                    return render(request, 'signinaout/register.html', locals())

                new_user = models.User()
                new_user.name = username
                new_user.password = hash_code(password1)
                new_user.email = email
                new_user.sex = sex
                new_user.head_image = head_image
                new_user.head_image.name = new_user.name + datetime.datetime.now().strftime('%Y%m%d%H%m') + '.' + new_user.head_image.name.split('.')[-1]
                new_user.save()

                # 生成邮箱确认码
                code = make_confirm_string(new_user)
                # 发送确认码
                send_email(email,code)

                message = '请前往邮箱进行确认'

                return redirect('/info/login/')
        else:
            return render(request,'signinaout/register.html',locals())
    # 如果没有登录并且没有上传信息
    register_form = forms.RegisterForm()
    return render(request,'signinaout/register.html',locals())

def changes(request):
    name = request.session['user_name']
    user = models.User.objects.get(name=name)
    message = '请检查填写的内容！'
    if request.method == 'POST':
        # 实例化表单
        change_form = forms.ChangeForm(request.POST)
        if change_form.is_valid():
            print('已经进入校验')
            email = change_form.cleaned_data.get('email')
            sex = change_form.cleaned_data.get('sex')
            models.User.objects.filter(name=user.name).update(sex=sex,email=email)
            # return redirect('/signinaout/')
    change_form = forms.ChangeForm()
    return render(request,'signinaout/changes.html',locals())
# user_confirm func
def user_confirm(request):
    # 从用户在邮件中点击的连接中获取验证码
    code = request.GET.get('code',None)
    message = ''
    try:
        confirm = models.ConfirmString.objects.get(code=code)
    except:
        # 如果找不到对应确认码的用户，进行反馈
        message = '无效的确认请求！'
        return render(request,'signinaout/confirm.html',locals())

    c_time = confirm.c_time
    now = datetime.datetime.now()
    # 如果现在的时间已经超过了确认码的有效期限，则反馈重新注册
    if now > c_time + datetime.timedelta(settings.CONFIRM_DAYS):
        confirm.user.delete()
        message = '您的邮件已经过期！请重新注册！'
        return render(request,'signinaout/confirm.html',locals())
    else:
        # 如果还在有效期内，则将用户状态改为已确认，并保存用户信息，删除确认码
        confirm.user.has_confirmed = True
        confirm.user.save()
        confirm.delete()
        message = '确认完成，请使用账户登录！'
        return render(request,'signinaout/confirm.html',locals())

def change_password_confirm(request):
    # 从用户在邮件中点击的连接中获取验证码
    code = request.GET.get('code',None)
    new_password = request.GET.get('new', None)
    message = ''
    try:
        confirm = models.ChangePasswordConfirmString.objects.get(code=code)
    except:
        # 如果找不到对应确认码的用户，进行反馈
        message = '无效的确认请求！'
        return render(request,'signinaout/change_password_confirm.html',locals())

    c_time = confirm.c_time
    now = datetime.datetime.now()
    # 如果现在的时间已经超过了确认码的有效期限，则反馈重新注册
    if now > c_time + datetime.timedelta(settings.CONFIRM_DAYS):
        confirm.user.delete()
        message = '您的邮件已经过期！请重新申请修改密码！'
        return render(request,'signinaout/change_password_confirm.html',locals())
    else:
        # 如果还在有效期内，则将用户状态改为已确认，并保存用户信息，删除确认码
        confirm.user.password = new_password
        confirm.user.save()
        confirm.delete()
        message = '确认完成，请使用账户登录！'
        return render(request,'signinaout/change_password_confirm.html',locals())


def idconfirm(request):
    name = request.session['user_name']
    user = models.User.objects.get(name=name)
    message = '请上传身份信息图片'
    if request.method == 'POST':
        # 实例化表单
        idchecked_form = forms.IdCkeckForm(request.POST,request.FILES)
        if idchecked_form.is_valid():
            print('已经进入校验')
            idchecked_form = idchecked_form.cleaned_data.get('check_image')
            user.check_image = idchecked_form
            user.check_image.name = user.name + '校验' + datetime.datetime.now().strftime('%Y%m%d%H%m') + '.' + \
                                       user.check_image.name.split('.')[-1]
            user.save()

后端/Club/ClubWeb/signinaout/templates/signinaout/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码</title>
</head>
<body>
<div>
    <h2>
        Page of change password
    </h2>
    <form action="/info/change_password/" method="post" enctype="multipart/form-data">
        {% if change_password_form.captcha.errors %}
            <div>{{ change_password_form.captcha.errors }}</div>
        {% elif message %}
            <div>{{ message }}</div>
        {% endif %}
        {% csrf_token %}
        <h3 class="text-center">输入邮箱、原密码与新密码并点击确认以修改密码</h3>
            <div>
                {{ change_password_form.email.label_tag }}
                {{ change_password_form.email }}
            </div>
            <div>
                {{ change_password_form.new_password.label_tag }}
                {{ change_password_form.new_password }}
            </div>
<!--            <div>-->
<!--                {{ change_password_form.old_password.label_tag }}-->
<!--                {{ change_password_form.old_password }}-->
<!--            </div>-->
            <div class="form-group">
                {{ change_password_form.captcha.label_tag }}
                {{ change_password_form.captcha }}
            </div>
            <div>
                <a href="/info/login/"><ins>直接登录</ins></a>
                <a href="/info/register/"><ins>注册新账号</ins></a>
                <button type="submit">确认修改</button>
            </div>
    </form>
    <p>
        <a href="{% url 'allclub:index' %}">
            返回
        </a>
    </p>

</div>
</body>
</html>

后端/Club/ClubWeb/signinaout/templates/signinaout/change_password_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码确认</title>
</head>
<body>
    <div>
        <h1>
            {{ message }}
        </h1>
    </div>
    <script>
        window.setTimeout("window.location='/info/login/'",2000);;
    </script>
</body>
</html>

后端/Club/ClubWeb/signinaout/templates/signinaout/changes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <p>
        Page of changes
    </p>
    <div>
        <form action="/info/changes/" method="post">
            {% csrf_token %}
            <h3 class="text-center">修改个人信息</h3>
            <div>
                {{ change_form.email.label_tag }}
                {{ change_form.email }}
            </div>
            <div>
                {{ change_form.sex.label_tag }}
                {{ change_form.sex }}
            </div>
            <div>
                <button type="submit">确认修改</button>
            </div>
        </form>
    </div>
    <p>
        <a href="{% url 'allclub:index' %}">
            返回
        </a>
    </p>
</div>
</body>
</html>

后端/Club/ClubWeb/signinaout/templates/signinaout/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册确认</title>
</head>
<body>
    <div>
        <h1>
            {{ message }}
        </h1>
    </div>
    <script>
        window.setTimeout("window.location='/info/login/'",2000);;
    </script>
</body>
</html>

后端/Club/ClubWeb/signinaout/templates/signinaout/idconfirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <div>
        {% if request.session.is_uploaded == True %}
            {{ message }}
        {% endif %}
    </div>
    <div>
        <form action="/info/idconfirm/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h3 class="text-center">上传身份信息</h3>
            <div>
                {{ idchecked_form.check_image.label_tag }}
                {{ idchecked_form.check_image }}
            </div>
            <div>
                <button type="submit">上传</button>
            </div>
        </form>
    </div>
    <p>
        <a href="{% url 'allclub:index' %}">
            返回
        </a>
    </p>

</div>
</body>
</html>

后端/Club/ClubWeb/signinaout/templates/signinaout/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
    <div>
        <div>
            <form action="/info/login/" method="post">
                {% if login_form.captcha.errors %}
                    <div>{{ login_form.captcha.errors }}</div>
                {% elif message %}
                    <div>{{ message }}</div>
                {% endif %}
<!--                {% if message %}-->
<!--                        <div class="alert alert-warning">{{ message }}</div>-->
<!--                {% endif %}-->
                {% csrf_token %}
                <h3>欢迎登录</h3>
                <div>
                    {{ login_form.username.label_tag }}
                    {{ login_form.username }}
                </div>
                <div>
                    {{ login_form.password.label_tag }}
                    {{ login_form.password }}
                </div>
                <div>
                    {{ login_form.captcha.label_tag }}
                    {{ login_form.captcha }}
                </div>

                <div>
                    <button type="submit">登录</button>
                    <br>
                    <br>
                    <a href="/info/register"><ins>新用户注册</ins></a>
                    <a href="/info/change_password"><ins>忘记密码</ins></a>
                </div>
            </form>
        </div>

        <div>
            <a href="{% url 'allclub:index' %}">
                返回
            </a>
        </div>
    </div>
</body>
</html>

后端/Club/ClubWeb/signinaout/templates/signinaout/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>
        <h1>
            页面将于3秒后跳转至首页
        </h1>
        <div>
            <h3>
                <a href="{% url 'allclub:index' %}">如果页面没有自动跳转可以点击这里返回首页</a>
            </h3>
        </div>
    </div>
    <script>
    window.setTimeout("window.location='/allclubs/'",2000);;
    </script>
</body>
</html>

后端/Club/ClubWeb/signinaout/templates/signinaout/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
<div>
    <h2>
        Page of register
    </h2>
    <form action="/info/register/" method="post" enctype="multipart/form-data">
        {% if register_form.captcha.errors %}
            <div>{{ register_form.captcha.errors }}</div>
        {% elif message %}
            <div>{{ message }}</div>
        {% endif %}
        {% csrf_token %}
        <h3 class="text-center">欢迎注册</h3>
            <div>
                {{ register_form.username.label_tag }}
                {{ register_form.username}}
            </div>
            <div>
                {{ register_form.password1.label_tag }}
                {{ register_form.password1 }}
            </div>
            <div>
                {{ register_form.password2.label_tag }}
                {{ register_form.password2 }}
            </div>
            <div>
                {{ register_form.email.label_tag }}
                {{ register_form.email }}
            </div>
            <div>
                {{ register_form.sex.label_tag }}
                {{ register_form.sex }}
            </div>
            <div>
                {{ register_form.head_image.label_tag }}
                {{ register_form.head_image }}
            </div>
            <div class="form-group">
                {{ register_form.captcha.label_tag }}
                {{ register_form.captcha }}
            </div>
            <div>
                <a href="/info/login/"><ins>直接登录</ins></a>
                <button type="submit">注册</button>
            </div>
    </form>
    <p>
        <a href="{% url 'allclub:index' %}">
            返回
        </a>
    </p>

</div>
</body>
</html>