后端/Club/ClubWeb/activity/urls.py
from django.urls import path

from . import views

app_name = 'activity'

urlpatterns = [
    path('',views.clubactive,name='activity'),
    path('<str:title>',views.activity_detail,name='detail'),
    path('comment/',views.comment, name='comment'),
]

后端/Club/ClubWeb/chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
   path('', views.index, name='index'),
   path('<str:room_name>/', views.room, name='room'),
   path('one2one/<str:one2oneroom_name>/',views.one,name='one2oneroom')
]

后端/Club/ClubWeb/signinaout/urls.py
from django.urls import path,include

from . import views

app_name = 'signinaout'

urlpatterns = [
    path('login/', views.login,name='login'),
    path('logout/', views.logout,name='logout'),
    path('register/', views.register,name='register'),
    path('changes/',views.changes,name='changes'),
    path('confirm/',views.user_confirm,name='comfirm'),
    path('idconfirm/',views.idconfirm,name='idconfirm'),
    path('change_password/',views.change_password,name='change_password'),
    path('change_password_confirm/',views.change_password_confirm,name='change_password_confirm'),
]

后端/Club/ClubWeb/activity/models.py
from django.db import models

from signinaout.models import User

# Create your models here.
class Activity(models.Model):
    title = models.CharField(max_length=255)
    context = models.TextField()
    publisher = models.ForeignKey(User,on_delete=models.CASCADE,default='bbb')
    publish_time = models.DateTimeField(auto_now_add=True)
    change_time = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

class Comment(models.Model):
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE,verbose_name="评论文章")
    comment_context = models.TextField(verbose_name="评论内容")
    comment_author = models.ForeignKey(User, on_delete=models.DO_NOTHING,verbose_name="评论者")
    comment_time = models.DateTimeField(auto_now_add=True, verbose_name="评论时间")
    pre_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, verbose_name="父评论")

    def __str__(self):
        return self.comment_context

    class Mete:
        verbose_name = "评论"
        verbose_name_plural = verbose_name

后端/Club/ClubWeb/activity/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse

from .models import Activity,Comment
# Create your views here.

def clubactive(request):
    activities = Activity.objects.all()
    return render(request,'activity/activity.html',locals())

def activity_detail(request,title):
    activity = Activity.objects.get(title = title)
    comment_list = Comment.objects.filter(activity_id = activity.pk)
    return render(request,'activity/detail.html',locals())

def comment(request):
    if request.session["user_id"]:
        comment_context = request.POST.get('comment_context')
        activity_id = request.POST.get('activity_id')
        pid = request.POST.get('pid')
        author_id = request.session["user_id"]
        Comment.objects.create(comment_context=comment_context, pre_comment_id=pid, activity_id=activity_id,comment_author_id=author_id)
        activity = list(Comment.objects.values('id','comment_context','pre_comment_id','activity_id','comment_author_id','comment_time'))
        return JsonResponse(activity, safe=False)
    else:
        return redirect('/info/login/')

后端/Club/ClubWeb/activity/templates/activity/activity.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Club Activities</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <style>
        /* Make the image fully responsive */
        .carousel-inner img {
          width: 100%;
          height: 100%;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
        <a class="navbar-brand" href="/allclubs/">HOME</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/allclubs/">All Clubs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'activity:activity' %}">Club Activities</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto" >
            {% if request.session.user_name %}
                <li>
                    <img src="{{ user.head_image.url }}"></img>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">{{ request.session.user_name }}!  欢迎回来！</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'signinaout:idconfirm' %}">校园身份验证</a>
                        <a class="dropdown-item" href="{% url 'signinaout:changes' %}">修改个人信息</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signinaout:logout' %}">退出</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signinaout:login' %}">登录</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signinaout:register' %}">注册</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    <div class="container-fluid" style="margin-top:80px">
        <div class="card">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h2>All Activities</h2>
                </div>
            </div>
        {% for activity in activities %}
            <div class="card">
                <div class="card-body">
                    <a href="{% url 'activity:detail' activity.title %}">{{activity.title}}</a>
                    <p>{{activity.publisher}}</p>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
    </div>

</body>
</html>

后端/Club/ClubWeb/activity/templates/activity/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>activity detail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <style>
        /* Make the image fully responsive */
        .carousel-inner img {
          width: 100%;
          height: 100%;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
        <a class="navbar-brand" href="/allclubs/">HOME</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/allclubs/">All Clubs</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'activity:activity' %}">Club Activities</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto" >
            {% if request.session.user_name %}
                <li>
                    <img src="{{ user.head_image.url }}"></img>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">{{ request.session.user_name }}!  欢迎回来！</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'signinaout:idconfirm' %}">校园身份验证</a>
                        <a class="dropdown-item" href="{% url 'signinaout:changes' %}">修改个人信息</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signinaout:logout' %}">退出</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signinaout:login' %}">登录</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signinaout:register' %}">注册</a>
                </li>
            {% endif %}
        </ul>
    </nav>
<div class="container-fluid" style="margin-top:80px">
    <div class="card">
        <div class="card-body">
            <div>
                <h1>{{ activity.title }}</h1>
                <br>
                <h4>发布者：{{ activity.publisher }}</h4>
                <h4>创建时间：{{ activity.publish_time }}</h4>
                <h4>修改时间：{{ activity.change_time }}</h4>
            </div>
            <div>
                <p>
                    {{ activity.context }}
                </p>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h3>评论区</h3>
            <div class="comment_post">
                <div id="commentform_title">
                    <p id="comment_message"></p>
                    <textarea rows="10" cols="60" id="comment_context"></textarea>
                    {% csrf_token %}
                    <p><button>提交评论</button></p>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="comment_show">
                <div class="feedback_area_title">
                    评论列表
                </div>
                <div class="comment_list">
                    {% for comment in comment_list %}
                        <div>
                            <p>第{{ forloop.counter}}楼 -> By:{{ comment.comment_author.name }}    {{ comment.comment_time }}    <button class="reply" name="{{ comment.comment_author.name }}" pk = "{{ comment.pk }}">回复</button></p>
                            {% if comment.pre_comment_id %}
                                <p>
                                    原评论内容：{{ comment.pre_comment.comment_context }}
                                </p>
                            {% endif %}
                            <p>
                                评论内容：{{ comment.comment_context }}
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
    <script>
            var token = $('input[name=csrfmiddlewaretoken]').val();
            var pid = ""
            $(".comment_post p button").click(function (){
                $.ajax({
                    url: '/activity/comment/',
                    type: 'post',
                    data: {
                        csrfmiddlewaretoken: token,
                        comment_context: $("#comment_context").val(),
                        activity_id: {{ activity.pk }},
                        pid: pid
                    },
                    success: function (res){
                        console.log(res)
                        $("#comment_message").html($("#comment_message").html() + "已成功回复")
                        for(let i = 0;i < 5000;i++){}
                        window.location.reload()
                        $("#comment_context").val("")
                        pid = ""
                    }
                })
            })
            $(".reply").click(function (){
                $("#comment_context").focus()
                var val = "@" + $(this).attr("name") + "\n"
                $("#comment_context").val(val)
                pid = $(this).attr("pk")
            })
    </script>
</body>
</html>